// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SertecDashboard.Api.Data;

#nullable disable

namespace SertecDashboard.Api.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        modelBuilder.Entity("SertecDashboard.Api.Models.Alert", b =>
        {
            b.Property<string>("Id").HasMaxLength(32).HasColumnType("nvarchar(32)");
            b.Property<bool>("Acknowledged").HasDefaultValue(false).HasColumnType("bit");
            b.Property<string>("OperatorName").HasMaxLength(100).HasColumnType("nvarchar(100)").IsRequired();
            b.Property<string>("OperatorUsername").HasMaxLength(50).HasColumnType("nvarchar(50)").IsRequired();
            b.Property<string>("PendingId").HasMaxLength(32).HasColumnType("nvarchar(32)");
            b.Property<string>("QuestionText").HasMaxLength(500).HasColumnType("nvarchar(500)").IsRequired();
            b.Property<string>("ShiftId").HasMaxLength(32).HasColumnType("nvarchar(32)");
            b.Property<string>("Time").HasMaxLength(50).HasColumnType("nvarchar(50)").IsRequired();
            b.Property<long>("TimeMs").HasColumnType("bigint");
            b.Property<string>("Type").HasMaxLength(30).HasDefaultValue("missed_question").HasColumnType("nvarchar(30)").IsRequired();
            b.HasKey("Id");
            b.HasIndex("Acknowledged");
            b.ToTable("alerts");
        });

        modelBuilder.Entity("SertecDashboard.Api.Models.AppUser", b =>
        {
            b.Property<string>("Username").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("DisplayName").HasMaxLength(100).HasColumnType("nvarchar(100)").IsRequired();
            b.Property<string>("Email").HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("PasswordHash").HasMaxLength(256).HasColumnType("nvarchar(256)").IsRequired();
            b.Property<string>("Role").HasMaxLength(30).HasColumnType("nvarchar(30)").IsRequired();
            b.HasKey("Username");
            b.ToTable("users");
        });

        modelBuilder.Entity("SertecDashboard.Api.Models.Document", b =>
        {
            b.Property<string>("Id").HasMaxLength(32).HasColumnType("nvarchar(32)");
            b.Property<string>("Data").HasColumnType("nvarchar(max)").IsRequired();
            b.Property<string>("Name").HasMaxLength(200).HasColumnType("nvarchar(200)").IsRequired();
            b.Property<string>("Size").HasMaxLength(50).HasColumnType("nvarchar(50)").IsRequired();
            b.Property<string>("UploadedAt").HasMaxLength(50).HasColumnType("nvarchar(50)").IsRequired();
            b.HasKey("Id");
            b.ToTable("documents");
        });

        modelBuilder.Entity("SertecDashboard.Api.Models.Machine", b =>
        {
            b.Property<string>("Id").HasMaxLength(32).HasColumnType("nvarchar(32)");
            b.Property<string>("Name").HasMaxLength(100).HasColumnType("nvarchar(100)").IsRequired();
            b.HasKey("Id");
            b.ToTable("machines");
        });

        modelBuilder.Entity("SertecDashboard.Api.Models.MachinePart", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int")
             .HasAnnotation("SqlServer:Identity", "1, 1");
            b.Property<string>("MachineId").HasMaxLength(32).HasColumnType("nvarchar(32)").IsRequired();
            b.Property<string>("Name").HasMaxLength(200).HasColumnType("nvarchar(200)").IsRequired();
            b.HasKey("Id");
            b.HasIndex("MachineId");
            b.ToTable("machineparts");
        });

        modelBuilder.Entity("SertecDashboard.Api.Models.PasswordReset", b =>
        {
            b.Property<string>("Id").HasMaxLength(32).HasColumnType("nvarchar(32)");
            b.Property<string>("DisplayName").HasMaxLength(100).HasColumnType("nvarchar(100)").IsRequired();
            b.Property<bool>("Handled").HasDefaultValue(false).HasColumnType("bit");
            b.Property<string>("HandledAt").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<long>("RequestedAtMs").HasColumnType("bigint");
            b.Property<string>("RequestedAt").HasMaxLength(50).HasColumnType("nvarchar(50)").IsRequired();
            b.Property<string>("Role").HasMaxLength(30).HasColumnType("nvarchar(30)").IsRequired();
            b.Property<string>("Username").HasMaxLength(50).HasColumnType("nvarchar(50)").IsRequired();
            b.HasKey("Id");
            b.HasIndex("Handled");
            b.ToTable("passwordresets");
        });

        modelBuilder.Entity("SertecDashboard.Api.Models.PendingItem", b =>
        {
            b.Property<string>("Id").HasMaxLength(32).HasColumnType("nvarchar(32)");
            b.Property<string>("AlertAnswer").HasMaxLength(5).HasDefaultValue("no").HasColumnType("nvarchar(5)").IsRequired();
            b.Property<bool>("AlertSent").HasDefaultValue(false).HasColumnType("bit");
            b.Property<long>("AnswerWindowMs").HasDefaultValue(600000L).HasColumnType("bigint");
            b.Property<long>("Deadline").HasColumnType("bigint");
            b.Property<bool>("Expired").HasDefaultValue(false).HasColumnType("bit");
            b.Property<string>("NoLabel").HasMaxLength(50).HasDefaultValue("Nem").HasColumnType("nvarchar(50)").IsRequired();
            b.Property<string>("QuestionId").HasMaxLength(32).HasColumnType("nvarchar(32)").IsRequired();
            b.Property<string>("RequireExplanation").HasMaxLength(10).HasDefaultValue("no").HasColumnType("nvarchar(10)").IsRequired();
            b.Property<string>("SentAt").HasMaxLength(50).HasColumnType("nvarchar(50)").IsRequired();
            b.Property<long>("SentAtMs").HasColumnType("bigint");
            b.Property<string>("SentBy").HasMaxLength(10).HasDefaultValue("auto").HasColumnType("nvarchar(10)").IsRequired();
            b.Property<string>("ShiftId").HasMaxLength(32).HasColumnType("nvarchar(32)");
            b.Property<string>("TargetOperator").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("TargetOperatorName").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("Text").HasMaxLength(500).HasColumnType("nvarchar(500)").IsRequired();
            b.Property<string>("YesLabel").HasMaxLength(50).HasDefaultValue("Igen").HasColumnType("nvarchar(50)").IsRequired();
            b.HasKey("Id");
            b.HasIndex("Expired");
            b.ToTable("pendingitems");
        });

        modelBuilder.Entity("SertecDashboard.Api.Models.Question", b =>
        {
            b.Property<string>("Id").HasMaxLength(32).HasColumnType("nvarchar(32)");
            b.Property<string>("AlertAnswer").HasMaxLength(5).HasDefaultValue("no").HasColumnType("nvarchar(5)").IsRequired();
            b.Property<long>("AnswerWindowMs").HasDefaultValue(600000L).HasColumnType("bigint");
            b.Property<string>("CreatedAt").HasMaxLength(50).HasColumnType("nvarchar(50)").IsRequired();
            b.Property<string>("Freq").HasMaxLength(30).HasDefaultValue("Every 1 hour").HasColumnType("nvarchar(30)").IsRequired();
            b.Property<long>("LastSent").HasDefaultValue(0L).HasColumnType("bigint");
            b.Property<long>("LastShiftSentMs").HasDefaultValue(0L).HasColumnType("bigint");
            b.Property<string>("NoLabel").HasMaxLength(50).HasDefaultValue("Nem").HasColumnType("nvarchar(50)").IsRequired();
            b.Property<string>("RequireExplanation").HasMaxLength(10).HasDefaultValue("no").HasColumnType("nvarchar(10)").IsRequired();
            b.Property<string>("Text").HasMaxLength(500).HasColumnType("nvarchar(500)").IsRequired();
            b.Property<string>("Type").HasMaxLength(30).HasDefaultValue("production").HasColumnType("nvarchar(30)").IsRequired();
            b.Property<string>("YesLabel").HasMaxLength(50).HasDefaultValue("Igen").HasColumnType("nvarchar(50)").IsRequired();
            b.HasKey("Id");
            b.ToTable("questions");
        });

        modelBuilder.Entity("SertecDashboard.Api.Models.QuestionResponse", b =>
        {
            b.Property<string>("Id").HasMaxLength(32).HasColumnType("nvarchar(32)");
            b.Property<string>("AlertAnswer").HasMaxLength(5).HasDefaultValue("no").HasColumnType("nvarchar(5)").IsRequired();
            b.Property<string>("Answer").HasMaxLength(5).HasColumnType("nvarchar(5)").IsRequired();
            b.Property<string>("Operator").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("OperatorName").HasMaxLength(100).HasDefaultValue("Operator").HasColumnType("nvarchar(100)").IsRequired();
            b.Property<string>("PendingId").HasMaxLength(32).HasColumnType("nvarchar(32)");
            b.Property<string>("Question").HasMaxLength(500).HasColumnType("nvarchar(500)").IsRequired();
            b.Property<string>("Reason").HasMaxLength(1000).HasColumnType("nvarchar(1000)").IsRequired();
            b.Property<string>("Time").HasMaxLength(50).HasColumnType("nvarchar(50)").IsRequired();
            b.Property<long>("TimeMs").HasColumnType("bigint");
            b.HasKey("Id");
            b.HasIndex("Operator");
            b.HasIndex("TimeMs");
            b.ToTable("responses");
        });

        modelBuilder.Entity("SertecDashboard.Api.Models.Shift", b =>
        {
            b.Property<string>("Id").HasMaxLength(32).HasColumnType("nvarchar(32)");
            b.Property<bool>("Active").HasDefaultValue(true).HasColumnType("bit");
            b.Property<string>("EndedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<long?>("EndTime").HasColumnType("bigint");
            b.Property<string>("EndTimeStr").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("OperatorName").HasMaxLength(100).HasColumnType("nvarchar(100)").IsRequired();
            b.Property<string>("OperatorUsername").HasMaxLength(50).HasColumnType("nvarchar(50)").IsRequired();
            b.Property<string>("Report").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
            b.Property<string>("Role").HasMaxLength(30).HasColumnType("nvarchar(30)").IsRequired();
            b.Property<long>("StartTime").HasColumnType("bigint");
            b.Property<string>("StartTimeStr").HasMaxLength(50).HasColumnType("nvarchar(50)").IsRequired();
            b.HasKey("Id");
            b.HasIndex("Active");
            b.ToTable("shifts");
        });

        modelBuilder.Entity("SertecDashboard.Api.Models.MachinePart", b =>
        {
            b.HasOne("SertecDashboard.Api.Models.Machine", "Machine")
             .WithMany("Parts")
             .HasForeignKey("MachineId")
             .OnDelete(DeleteBehavior.Cascade)
             .IsRequired();
            b.Navigation("Machine");
        });

        modelBuilder.Entity("SertecDashboard.Api.Models.Machine", b =>
            b.Navigation("Parts"));
#pragma warning restore 612, 618
    }
}
